import clientColumns from '@/config/client-columns.json';
import { normalizeState, normalizeDate, normalizeZip } from './normalize';
import { deriveLegalEntity } from './company';
import type { ClassifiedLearner, TrainingEvent } from './types';

/** Build one 105-column client import row. Rules: import-process-steps.md + SKILL.md June 2026 overrides. */
export function buildClientRow(l: ClassifiedLearner, rowNo: number, trainings: TrainingEvent[]): string[] {
  const g = (name: string) => {
    const k = Object.keys(l.raw).find(h => h.toLowerCase() === name.toLowerCase());
    return k ? l.raw[k] : '';
  };
  const sessionDate = trainings.find(t => t.sourceFile === l.sourceFile)?.sessionDate
    || trainings[0]?.sessionDate || '';

  const v: Record<string, string> = {};
  v['No.'] = String(rowNo);
  v['UID'] = '';                                            // generated by GO upon import
  v['Center name'] = l.resolvedCenter;
  v['Advisor email'] = l.resolvedAdvisor;
  v['Client company'] = l.resolvedCompany;
  v['Manager first name'] = l.firstName;
  v['Manager last name'] = l.lastName;
  v['Company status'] = 'Active';                           // always-set
  v['Manager email'] = l.email;

  // Industry
  let industry = g('Type of business');
  if (industry === 'Services') industry = 'Other Services (except Public Administration)';
  if (industry === 'Finance, Insurance and Real Estate') industry = 'Finance and Insurance';
  v['Industry (primary)'] = industry || 'Other Services (except Public Administration)';

  v['City'] = g('City');
  v['State/Province'] = normalizeState(g('State'));
  const zip = normalizeZip(g('Zip Code'));
  v['Postal code'] = zip.postal;
  v['ZIP +4'] = zip.plus4;
  v['Municipality/County'] = l.county;
  v['Founded date'] = normalizeDate(g('Date business started?'));

  // Counselling: plain column stays BLANK (SKILL.md override); 641 gets the value
  v['Counselling seeking'] = '';
  const seeking = g('What are you interested in?') || 'Other';
  v['641 Counselling seeking'] = seeking;
  v['641 Counselling seeking (Other)'] = seeking === 'Other' ? 'Unknown/Not Stated' : '';

  v['Tags'] = 'Training';                                   // always-set

  const race = g('Race') || 'Prefer not to say';
  v['Race'] = race;
  v['641 Self-described Race'] = (race === 'Prefer to Self-Describe' || !g('Race')) ? 'Unknown/Not Stated' : '';

  let eth = g('Ethnicity');
  if (eth === 'Not Hispanic or Latino') eth = 'Non Hispanic or Latino';
  if (eth === 'Unknown/Not Stated') eth = 'Prefer not to say';
  v['Ethnicity'] = eth || 'Prefer not to say';

  const gender = g('Sex') || 'Prefer not to say';
  v['Gender'] = gender;
  v['641 Self-described Gender'] = '';                      // no longer used
  v['Disabled'] = g('Disability') || 'Prefer not to say';
  v['Veteran'] = '';                                        // SKILL.md: reserved, leave blank
  const mil = g('Military Status') || 'Prefer not to say';
  v['641 Military status'] = mil;
  v['641 Branch Of Service'] = 'Prefer not to say';         // SKILL.md June override
  v['641 Business Online'] = g('Online Business');
  v['641 8(a) Certified'] = g('Are you 8(a) certified?');

  const { legal, legalOther } = deriveLegalEntity(l.resolvedCompany);
  v['Legal entity'] = legal;
  v['641 Legal entity (Other)'] = legalOther;

  // Currently in business: only Yes/No when Founded date present, else Undetermined
  const founded = v['Founded date'];
  let cib = g('Currently in business');
  if (!founded) cib = 'Undetermined';
  else if (cib !== 'Yes' && cib !== 'No') cib = 'Undetermined';
  v['Currently in business'] = cib;

  v['Clients in international markets'] = g('Exporting');
  v['Total no. of employees (FT)'] = g('Total no. of employees (Full Time)');
  v['Total no. of employees (PT)'] = g('Total no. of employees (Part Time)');

  // Export countries: strip USA/US/United States
  let exp = g('If yes, to which countries are you exporting');
  if (exp) {
    const parts = exp.split(/[,;]+/).map(s => s.trim())
      .filter(s => s && !['usa','us','united states'].includes(s.toLowerCase()));
    exp = parts.join(', ');
  }
  v['641 Export Countries'] = exp;
  v['641 Employees engaged in exporting'] = g('Employees engaged in exporting (Full Time & Part Time)');

  v['641 Referral from'] = 'Other';
  v['641 Referral from (Other)'] = 'Unknown/Not Stated';
  v['641 Agreement'] = 'Yes';
  v['641 Client Signature'] = 'Yes';
  v['641 Client Signature Date'] = sessionDate;
  v['Language'] = 'English';
  v['Counseling language'] = 'English';
  v['Intake form signature'] = `${l.firstName} ${l.lastName}`.trim();

  // Conditional defaults when Currently in business = Yes
  if (v['Currently in business'] === 'Yes') {
    if (!v['Total no. of employees (FT)']) v['Total no. of employees (FT)'] = '1';
    if (!v['Total no. of employees (PT)']) v['Total no. of employees (PT)'] = '0';
    if (!v['Clients in international markets']) v['Clients in international markets'] = 'No';
    if (!v['641 Business Online']) v['641 Business Online'] = 'No';
    if (!v['641 8(a) Certified']) v['641 8(a) Certified'] = 'No';
    if (!v['Female ownership %']) {
      if (gender === 'Female') v['Female ownership %'] = '100';
      else if (gender === 'Male') v['Female ownership %'] = '0';
    }
  }

  return (clientColumns as string[]).map(c => v[c] ?? '');
}
